# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

pool:
  vmImage: 'Ubuntu-16.04'

variables:
  buildConfiguration: 'release'
  major: 0
  minor: 0
  patch: $[counter(format('{0}.{1}', variables['major'], variables['minor']), 0)]

steps:
- script: |
    dotnet build -c $(buildConfiguration)
    dotnet test jkulubya.lobrc.test -c $(buildConfiguration)
    dotnet pack src/jkulubya.lobrc.csproj -c $(buildConfiguration) /p:PackageVersion=$(major).$(minor).$(patch) --output $(Build.ArtifactStagingDirectory) --no-build --no-restore
  condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))

- script: |
    dotnet build -c $(buildConfiguration)
    dotnet test jkulubya.lobrc.test -c $(buildConfiguration)
    dotnet pack src/jkulubya.lobrc.csproj -c $(buildConfiguration) /p:PackageVersion=$(major).$(minor).$(patch) --output $(Build.ArtifactStagingDirectory) --no-build --no-restore
  condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/dev'))

- script: |
    dotnet build -c $(buildConfiguration)
    dotnet test jkulubya.lobrc.test -c $(buildConfiguration)
  condition: and(succeeded(), and(ne(variables['Build.SourceBranch'], 'refs/heads/master'), ne(variables['Build.SourceBranch'], 'refs/heads/dev')))

- task: NuGetCommand@2
  inputs:
    command: 'push'
    searchPatternPush: '$(Build.ArtifactStagingDirectory)/**/*.nupkg;$(Build.ArtifactStagingDirectory)/**/*.snupkg'
    nuGetFeedType: 'external'
    externalEndpoint: 'a065c124-0a41-4722-9236-fe2199204978'
  condition: and(succeeded(), or(eq(variables['Build.SourceBranch'], 'refs/heads/master'), eq(variables['Build.SourceBranch'], 'refs/heads/dev')))
  